services:
  - type: web
    name: attendly
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate --noinput
    startCommand: gunicorn config.wsgi:application --log-file -
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_HOSTS
        value: "attendly.onrender.com,localhost,127.0.0.1"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://attendly.onrender.com"
      - key: PYTHON_VERSION
        value: "3.11.9"
