# Generated by Django 5.2 on 2026-03-26 17:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_rename_email_to_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(
                10), django.core.validators.RegexValidator('^\\d+$', 'Mobile No must contain digits only.')]),
        ),
    ]
