# Generated by Django 6.0.3 on 2026-03-26 17:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_remove_student_id_alter_student_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator('^\\d+$', 'Mobile No must contain digits only.')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=20),
        ),
    ]
